#ifndef STEP_MANAGER_DEFS_H
#define STEP_MANAGER_DEFS_H

#define LOWSIDE_PHASE_A (GPIO_PIN_13)
#define LOWSIDE_PHASE_B (GPIO_PIN_14)
#define LOWSIDE_PHASE_C (GPIO_PIN_15)

#define HIGHSIDE_PHASE_A (TIM_CHANNEL_1)
#define HIGHSIDE_PHASE_B (TIM_CHANNEL_2)
#define HIGHSIDE_PHASE_C (TIM_CHANNEL_3)

#define ADC_PHASE_A (ADC_CHANNEL_0)
#define ADC_PHASE_B (ADC_CHANNEL_1)
#define ADC_PHASE_C (ADC_CHANNEL_2)


//ALIGNMENT STATE DEFINITION
#define ALIGNMENT_CURRENT_REF 150 // = 0.5A on a 50A scale mapped to 12-bit ADC max of 4095
#define ALIGNMENT_ARR (1000-1)
#define NUM_ALIGNMENT_PERIODS 10

//RAMP STATE DEFINITIONS
#define RAMP_CURRENT_REF 100
#define RAMP_TABLE_ENTRIES 34
#define RAMP_END_ENTRY 18 //which entry to stop ramp
#define RAMP_EXIT_CURRENT 15
#define NUM_RAMP_HOLD_STEPS 12
#define RAMP_HOLD_END_ENTRY (RAMP_END_ENTRY + NUM_RAMP_HOLD_STEPS)

////EXIT RAMP STATE DEFINITIONS
//#define BEMF_QUARTER_TILL_THRESH 30

//RUN STATE DEFINTIONS
#define ZC_DETECTIONS_FOR_VALID 1
#define BEMF_ZC_THRESH 50
#define DEMAG_NUM_PERIODS 6
#define RUN_W_CONTROL_INTERVAL 5
#endif //STEP_MANAGER_DEFS_H
